spring.application.name=inventory

# =========================
# DATABASE (Render PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://dpg-d7mv19gk1i2s739c3nf0-a.oregon-postgres.render.com:5432/inventory_50kp
spring.datasource.username=inventory_50kp_user
spring.datasource.password=2SHJesdhf3sNZ9wIYNTRlN6xTSW34fvn
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SESSION
# =========================
server.servlet.session.tracking-modes=cookie

# =========================
# RENDER PORT
# =========================
server.port=${PORT:8080}